### ISSUE TITLE
sembastFirestoreCodec codec not working on sembast 2.4.5

### ISSUE THREAD

**Issue by Tunga12** [tekartik/sembast_flutter_more.dart#7]
When i use the sembastFirestoreCodec with sembast 2.4.5 I get the following error:
DatabaseException ([2] Invalid codec signature).

pubsec.yaml:
`sembast: ^2.4.5
  sembast_cloud_firestore_type_adapters:
    git:
      url: git://github.com/tekartik/sembast_flutter_more.dart
      path: cloud_firestore_type_adapters
      ref: dart2
    version: '>=0.1.0'`

code Where I open the database:
`    final database = await databaseFactoryIo.openDatabase(dbPath, codec: sembastFirestoreCodec);
`

**Comment by SaltyPandaStudios** [comment]
For people who run into this later, wipe the database after adding the codec. It will fail to decode because the data in the database is stored with a different codec. 

That can close this issue, right?

**Comment by alextekartik** [comment]
You cannot change the codec if a database has been opened once. The only solution is to delete the database first before using a new codec
